server:
  port: 8080
  servlet:
    context-path: /logisticsSystem

spring:
  # 整合数据库
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/logisticsSystem?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    druid:
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      stat-view-servlet:
        allow: true
  # 整合Redis
  redis:
    database: 0
    # 主机号
    host: 127.0.0.1
    # 密码
    password: ##################
    # 端口号
    port: 6379
    # 什么时候超时
    timeout: 5000
    jedis:
      pool:
        max-active: 1000
        max-wait: -1
        max-idle: 10
        min-idle: 2
  resources:
    static-locations: classpath:templates/,classpath:static/
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.logistics.entity
  type-aliases-super-type: java.lang.Object
  # 配置逻辑删除
  global-config:
    db-config:
      id-type: auto
      # 逻辑删除 - 已经删除的值是1
      logic-delete-value: 1
      # 逻辑删除 - 没有删除的值是0
      logic-not-delete-value: 0



